config/routes.rb
Rails.application.routes.draw do
  root 'transactions#index'

  resources :transactions, only: [:index, :edit, :update] do
    collection do 
      get 'new/step1', to: 'transactions#step1'
      get 'new/step2', to: 'transactions#step2'
      post :validate_step
    end
      
    put :change_status
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
# frozen_string_literal: true

class Sale < ApplicationRecord
  include SaleState

  TRUCK = 'Truck'
  MUDDY_BED_FEE = 2

  before_save :set_amount
  after_create { pend! }

  paginates_per 10

  belongs_to :vehicle
  has_many :transitions, class_name: 'SaleTransition', autosave: false
  has_many :sale_transitions, class_name: 'SaleTransition', autosave: false

  accepts_nested_attributes_for :vehicle
  
  delegate :license_plate, :vehicle_type, to: :vehicle 
  delegate :allowed_transitions, :can_transition_to?, :transition_to!, :transition_to, :current_state,
    to: :state_machine

  validates_with BedValidator 
  
  def state_machine
    @state_machine ||= SaleStateMachine.new(self, transition_class: SaleTransition,
                                            association_name: :transitions)
  end

  private

  def set_amount
    self.amount = vehicle_type.price
    self.amount = amount + MUDDY_BED_FEE if vehicle_type.name == TRUCK && has_mud_on_bed
    
    sales = Sale.joins(:vehicle).where(vehicles: { license_plate: license_plate }).count

    self.amount = (amount / 2) if sales == 1 
  end
end

app/models/sale_transition.rb
# frozen_string_literal: true

class SaleTransition < ApplicationRecord
  include Statesman::Adapters::ActiveRecordTransition

  belongs_to :sale, inverse_of: :sale_transitions

  after_destroy :update_most_recent, if: :most_recent?

  private

  def update_most_recent
    last_transition = sale.sale_transitions.order(:sort_key).last
    return unless last_transition.present?
    last_transition.update_column(:most_recent, true)
  end
end

app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  TYPES = [[:car, 5], [:truck, 10]].freeze

  belongs_to :vehicle_type
  has_many :sales, dependent: :destroy

  validates_with LicensePlateValidator
  validates :license_plate, presence: true, uniqueness: true
  validates :vehicle_type_id, presence: true
end

app/models/vehicle_type.rb
# frozen_string_literal: true

class VehicleType < ApplicationRecord
  has_many :vehicles

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0 }

  def to_s
    name
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  class InvalidStep < StandardError; end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :load_step, except: %i[index edit update validate_license_plate validate_step change_status]

  def index
    session[:sale_params] = nil
    @sales = Sale.includes(vehicle: :vehicle_type).order('created_at desc').page(params[:page])
  end

  def edit
    @sale = Sale.find(params[:id])
  end

  def create
    if @step.sale.save
      session[:sale_params] = nil
      redirect_to transactions_url, notice: 'Transaction succesfully saved!'
    else
      redirect_to action: SaleFormModel::STEPS.first, alert: 'A problem occured while saving this transaction.'
    end
  end

  def update  
    @sale = Sale.find(params[:id])

    if @sale.update(sale_params.except('vehicle_attributes'))
      redirect_to edit_transaction_path(params[:id]), notice: 'Transaction successfully saved!'
    else
      render :edit
    end
  end

  def validate_step
    session[:sale_params] ||= {}
    session[:sale_params] = session[:sale_params].deep_merge(sale_params.as_json)
    @step = process_step(current_step)

    if @step.valid?
      next_step = next_step(current_step)
      create && return unless next_step
      redirect_to action: next_step
    else
      render current_step
    end
  end

  def change_status
    @sale = Sale.find(params[:transaction_id])

    case @sale.current_state
    when 'pending'
      @sale.start!
    when 'started'
      @sale.finish!
    when 'finished'
      @sale.pay!
    end

    redirect_to transactions_path, notice: 'Transaction successfully saved!'
  end

  private

  def load_step
    @step = process_step(action_name)
  end

  def next_step(step)
    SaleFormModel::STEPS[SaleFormModel::STEPS.index(step) + 1]
  end

  def process_step(step)
    raise InvalidStep unless step.in?(SaleFormModel::STEPS)

    "SaleFormModel::#{step.camelize}".constantize.new(session[:sale_params])
  end

  def sale_params 
    params.require(:sale).permit(:has_mud_on_bed, :with_bed_let_down,
                                 vehicle_attributes: %i[license_plate vehicle_type_id])
  end

  def current_step
    params[:current_step]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title CarWash

    meta charset='utf-8'

    = csrf_meta_tags

    /[if lt IE 9]
      script src='https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js'
      script src='https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js'
    
    = stylesheet_link_tag 'application', media: 'all'
    
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'

  body
    .container
      .header.clearfix
        nav
          ul.nav.nav-pills.float-right
            li.nav-item
              = link_to 'Transactions', transactions_path, class: 'nav-link'

        h3.text-muted Car Wash

      = yield

app/views/shared/_errors.html.slim
- if object.errors.any?
  .alert.alert-danger role='alert'
    h6 Please fix the following #{'error'.pluralize(object.errors.count)}: 

    ul
      - object.errors.full_messages.each do |msg|
        li= msg

app/views/shared/_notice.html.slim
- if flash[:notice].present?
  .row
    .col-lg-12
      .alert.alert-success.m-t-20 role='alert'
        = flash[:notice]

app/views/transactions/edit.html.slim
.row
  .col-lg-12
    h4.m-b-30 Edit Transaction ##{@sale.id} 

= render 'shared/notice'

.row
  .col-lg-12
    .highlight
      = form_for @sale, url: transaction_path do |f|
        = render partial: 'shared/errors', locals: { object: @sale }

        = f.fields_for :vehicle do |builder|
          - disable = !builder.object.new_record?

          .form-group
            = builder.label :license_plate
            = builder.text_field :license_plate, class: 'form-control', disabled: disable 
          
          .form-group
            = builder.label :type
            = builder.select :vehicle_type_id, VehicleType.all.collect { |v| [v.name, v.id] },
              { include_blank: true }, class: 'form-control custom-select', disabled: disable 

        .form-check
          .row
            .col-lg-6
              = f.label :has_mud_on_bed, class: 'form-check-label' do
                = f.check_box :has_mud_on_bed, class: 'form-check-input'
                | Has mud on bed?
            
            .col-lg-6
              = f.label :with_bed_let_down, class: 'form-check-label' do
                = f.check_box :with_bed_let_down, class: 'form-check-input'
                | With bed let down?

        br

        = link_to 'Back', transactions_path, class: 'btn btn-secondary', role: 'button'

        | &nbsp; &nbsp;
        
        = f.submit 'Continue', class: 'btn btn-primary btn-submit'

app/views/transactions/index.html.slim
.row
  .col-lg-12
    .float-right
      = link_to 'New Transaction', new_step1_transactions_path, class: 'btn btn-primary' 

= render 'shared/notice'

.row
  .col-lg-12
    .m-t-20
      table.table.table-hover
        thead.thead-default
          tr
            th #
            th License Plate
            th Type
            th Amount
            th Mud on Bed?
            th Bed Let Down?
            th &nbsp;

        tbody
          - @sales.each do |sale|
            tr
              td= sale.id
              td= link_to sale.license_plate, edit_transaction_path(sale)
              td= sale.vehicle_type
              td= number_to_currency(sale.amount)
              td= sale.has_mud_on_bed
              td= sale.with_bed_let_down
              td
                - unless sale.allowed_transitions.blank?
                  = link_to t(".links.sales.states.#{sale.allowed_transitions.first}"),
                    transaction_change_status_path(sale), method: :put, class: 'btn btn-success'

      .d-block.mx-auto= paginate(@sales)

app/views/transactions/new.html.slim
.row
  .col-lg-12
    h4.m-b-30 New Transaction

.row
  .col-lg-12
    = form_for @sale, url: transactions_path  do |f|
      = f.fields_for :vehicle do |builder|
        .form-group
          = builder.label :type
          = builder.select :type, Vehicle::TYPES.collect { |v| [v[0].to_s.titleize, v[0]] },
            { include_blank: true }, class: 'form-control custom-select'
        
        .form-group
          = builder.label :license_plate
          = builder.text_field :license_plate, class: 'form-control'

app/views/transactions/step1.html.slim
.row
  .col-lg-12
    h4.m-b-30 New Transaction Step 1 

.row
  .col-lg-12
    .highlight
      = form_for @step.sale, url: validate_step_transactions_path do |f|
        = render partial: 'shared/errors', locals: { object: @step }

        = hidden_field_tag :current_step, 'step1'

        = f.fields_for :vehicle do |builder|
          .form-group
            = builder.label :license_plate
            = builder.text_field :license_plate, class: 'form-control'

        = f.submit 'Continue', class: 'btn btn-primary btn-submit'

app/views/transactions/step2.html.slim
.row
  .col-lg-12
    h4.m-b-30 New Transaction Step 2

.row
  .col-lg-12
    .highlight
      = form_for @step.sale, as: :sale, url: validate_step_transactions_path do |f|
        = render partial: 'shared/errors', locals: { object: @step }

        = hidden_field_tag :current_step, 'step2'

        = f.fields_for :vehicle do |builder|
          .form-group
            = builder.label :type
            = builder.select :vehicle_type_id, VehicleType.all.collect { |v| [v.name, v.id] },
              { include_blank: true }, class: 'form-control custom-select', disabled: !builder.object.new_record?

        .form-check
          .row
            .col-lg-6
              = f.label :has_mud_on_bed, class: 'form-check-label' do
                = f.check_box :has_mud_on_bed, class: 'form-check-input'
                | Has mud on bed?
            
            .col-lg-6
              = f.label :with_bed_let_down, class: 'form-check-label' do
                = f.check_box :with_bed_let_down, class: 'form-check-input'
                | With bed let down?

        br

        = link_to 'Back', new_step1_transactions_path, class: 'btn btn-secondary', role: 'button'

        | &nbsp; &nbsp;

        = f.submit 'Continue', class: 'btn btn-primary btn-submit'